---
# defaults file for jdk

# Modifier la version du jdk si vous souhaiter installer une autre version de JDK
jdk_java_version: 1.8.0_141
jdk_versions: "/opt/jdk_versions"
jdk_java_home: "{{ jdk_versions }}/jdk{{ jdk_java_version }}"
# Modifier les noms des fichiers .tar.gz si on souhaite une autre version de JDK
jdk_tarball_name_32: jdk-8u141-linux-i586.tar.gz
jdk_tarball_name_64: jdk-8u141-linux-x64.tar.gz
# Modifier les URLs de téléchargement des JDKs si on souhaite une autre version de JDK
jdk_repo_url: "http://192.168.1.97:9081/nexus/content/repositories/releases"
jdk_32_url: "{{ jdk_repo_url }}/{{ jdk_tarball_name_32 }}"
jdk_64_url: "{{ jdk_repo_url }}/{{ jdk_tarball_name_64 }}"
