---
# tasks file for apps_api

- name: Stop eventual tomcat server running
  service:
    name: tomcat
    state: stopped
    enabled: no
  ignore_errors: true

- name: Créer les repertoires tomcat/conf/Catalina/ & tomcat/conf/Catalina/localhost
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes
  with_items:
    - "{{ tomcat_home }}/conf/Catalina"
    - "{{ tomcat_home }}/conf/Catalina/localhost"
    - "{{ apps_api_conf_directory }}"

- name: create log linkyboard directory
  file:
    path: "{{ apps_api_logs_directory }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: directory
    mode:  0750
    recurse: yes

- name: Supprimer le precedent war et le repertoires qui en était le résultat
  file:
   path: "{{ item }}"
   state: absent
  with_items:
      - "{{ tomcat_home }}/webapps/ROOT.war"
      - "{{ tomcat_home }}/webapps/ROOT"

- name: Télécharger la librairie postgres
  get_url:
    url: "{{ apps_api_nexus_releases_url }}/postgresql-9.4-1201-jdbc41.jar"
    dest: "{{ tomcat_home }}/lib/postgresql-9.4-1201-jdbc41.jar"
    mode: 0750

- name: Télécharger le fichier war de l'application
  get_url:
    url: "{{ apps_api_nexus_url }}?r={{ apps_api_repository }}&g={{ apps_api_groupid }}&a={{ apps_api_artifactid }}&v={{ apps_api_version }}&p={{ apps_api_package }}"
    dest: "{{ tomcat_home }}/webapps/ROOT.war"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0755

- name: copier les fichiers de configuration
  template:
    src: log4j.properties.j2
    dest: "{{ apps_api_conf_directory }}/log4j.properties"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: copier le fichier ROOT.xml
  template:
    src: ROOT.xml.j2
    dest: "{{ tomcat_home }}/conf/Catalina/localhost/ROOT.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: copier le fichier apps-config.properties
  template:
    src: apps-config.properties.j2
    dest: "{{ tomcat_home }}/conf/Catalina/localhost/apps-config.properties"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Restart tomcat
  command: echo "Restart Tomcat service"
  notify:
    - Restart tomcat