---
# defaults file for tomcat
repo_url: "http://192.168.1.97:9081/nexus"
tomcat_version: 8.0.32
tomcat_tarball_name: "apache-tomcat-{{ tomcat_version }}.tar.gz"
tomcat_url: "{{ repo_url }}/content/repositories/releases/{{ tomcat_tarball_name }}"
tomcat_home: "/opt/apache-tomcat-{{ tomcat_version }}"
tomcat_java_home: "/opt/jdk_versions/jdk1.8.0_131"
tomcat_libtcnative_util_home: "{{ tomcat_home }}/bin/tomcat-native-1.2.4-src/native"
tomcat_apr_config_file: "/usr/bin/apr-1-config"

tomcat_http_port: 8080
tomcat_https_port: 8443
tomcat_shutdown_port: "8005"
tomcat_mod_jk_port: 8009
tomcat_shutdown_command: "SHUTDOWNA1B2Z78UJHGJKLMLM"
tomcat_init_script: /etc/init.d/tomcat
tomcat_user: tomcat
tomcat_group: tomcat
tomcat_conf_directory: "{{ tomcat_home }}/conf"
tomcat_conf_files:
 - { src: "server.xml.j2", dest: "{{ tomcat_conf_directory }}/server.xml" }
 - { src: "setenv.sh.j2", dest: "{{ tomcat_home }}/bin/setenv.sh" }
 - { src: "web.xml.j2", dest: "{{ tomcat_conf_directory }}/web.xml" }
 - { src: "logging.properties.j2", dest: "{{ tomcat_conf_directory }}/logging.properties" }

tomcat_remove_files:
 - "webapps/ROOT/"
 - "webapps/examples/"
 - "webapps/host-manager/"
 - "webapps/manager/"
 - "conf/tomcat-users.xml"
 - "conf/tomcat-users.xsd"
 - "webapps/docs/"

tomcat_conf_server_info_dir: "org/apache/catalina/util"

tomcat_required_packages:
 - "libapr1"
 - "libapr1-dev"
 - "libaprutil1"
 - "libaprutil1-dev"
 - "libssl-dev"